# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Utility class for custom header authorization.
  class CustomHeaderAuth < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure in CustomAuthentication.
    # @returns [String] The oAuth error message.
    def error_message
      'CustomHeaderAuthentication: api_key is undefined.'
    end

    # Initialization constructor.
    def initialize(api_key)
      auth_params = {}
      auth_params['api_key'] = api_key unless api_key.nil?

      super auth_params

      @_api_key = api_key
    end
  end
end
