# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module SwaggerPetstoreOpenApi30
  # A utility  that supports dateTime conversion to different formats
  class DateTimeHelper < CoreLibrary::DateTimeHelper
  end
end
