# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Class for exceptions when there is a network error, status code error, etc.
  class APIException < CoreLibrary::ApiException
  end
end
