# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'swagger_petstore_open_api30'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include SwaggerPetstoreOpenApi30

  # Create configuration and set any test parameters
  def create_configuration
    Configuration.new(http_callback: HttpResponseCatcher.new)
  end

  # Initializes the base test controller
  def setup_class
    _config = create_configuration
    @client = Client.new(config: _config)
    _auth_managers = @client.auth_managers
  end
end
