# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class StoreControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.store
    @response_catcher = @controller.http_call_back
  end

  # Returns a map of status codes to quantities
  def test_get_inventory()

    # Perform the API call through the SDK function
    result = @controller.get_inventory()

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Place a new order in the store
  def test_place_order()
    # Parameters for the API call
    id = 10
    pet_id = 198772
    quantity = 7
    ship_date = DateTimeHelper.from_rfc3339('2023-05-31T00:00:00Z')
    order_status = 'approved'
    complete = true

    # Perform the API call through the SDK function
    result = @controller.place_order(id: id, pet_id: pet_id, quantity: quantity, ship_date: ship_date, order_status: order_status, complete: complete)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end
