# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class UserControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.user
    @response_catcher = @controller.http_call_back
  end

  # Creates list of users with given input array
  def test_create_users_with_list_input()
    # Parameters for the API call
    body = nil

    # Perform the API call through the SDK function
    result = @controller.create_users_with_list_input(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Logs user into the system
  def test_login_user()
    # Parameters for the API call
    username = nil
    password = nil

    # Perform the API call through the SDK function
    result = @controller.login_user(username: username, password: password)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['x-rate-limit'] = nil
    expected_headers['x-expires-after'] = nil
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end
