# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class PetControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.pet
    @response_catcher = @controller.http_call_back
  end

  # Multiple status values can be provided with comma separated strings
  def test_find_pets_by_status()
    # Parameters for the API call
    status = 'available'

    # Perform the API call through the SDK function
    result = @controller.find_pets_by_status(status: status)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
  def test_find_pets_by_tags()
    # Parameters for the API call
    tags = nil

    # Perform the API call through the SDK function
    result = @controller.find_pets_by_tags(tags: tags)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end
