# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstoreOpenApi30
  # Order Status
  class OrderStatusEnum
    ORDER_STATUS_ENUM = [
      # TODO: Write general description for PLACED
      PLACED = 'placed'.freeze,

      # TODO: Write general description for APPROVED
      APPROVED = 'approved'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze
    ].freeze
  end
end
