# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstoreOpenApi30
  # pet status in the store
  class PetStatusEnum
    PET_STATUS_ENUM = [
      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'available'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze,

      # TODO: Write general description for SOLD
      SOLD = 'sold'.freeze
    ].freeze
  end
end
