# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstoreOpenApi30
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
