# swagger_petstore_open_api30
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'
require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'
# rubocop:disable Style/MixinUsage
include CoreLibrary
# rubocop:enable Style/MixinUsage

require_relative 'swagger_petstore_open_api30/api_helper'
require_relative 'swagger_petstore_open_api30/client'

# Utilities
require_relative 'swagger_petstore_open_api30/utilities/file_wrapper'
require_relative 'swagger_petstore_open_api30/utilities/date_time_helper'

# Http
require_relative 'swagger_petstore_open_api30/http/http_call_back'
require_relative 'swagger_petstore_open_api30/http/http_method_enum'
require_relative 'swagger_petstore_open_api30/http/http_request'
require_relative 'swagger_petstore_open_api30/http/http_response'
require_relative 'swagger_petstore_open_api30/http/auth/custom_header_auth'

# Models
require_relative 'swagger_petstore_open_api30/models/base_model'
require_relative 'swagger_petstore_open_api30/models/order'
require_relative 'swagger_petstore_open_api30/models/customer'
require_relative 'swagger_petstore_open_api30/models/address'
require_relative 'swagger_petstore_open_api30/models/category'
require_relative 'swagger_petstore_open_api30/models/user'
require_relative 'swagger_petstore_open_api30/models/tag'
require_relative 'swagger_petstore_open_api30/models/pet'
require_relative 'swagger_petstore_open_api30/models/pet_image'
require_relative 'swagger_petstore_open_api30/models/order_status_enum'
require_relative 'swagger_petstore_open_api30/models/pet_status_enum'
require_relative 'swagger_petstore_open_api30/models/status_enum'

# Exceptions
require_relative 'swagger_petstore_open_api30/exceptions/api_exception'

require_relative 'swagger_petstore_open_api30/configuration'

# Controllers
require_relative 'swagger_petstore_open_api30/controllers/base_controller'
require_relative 'swagger_petstore_open_api30/controllers/pet_controller'
require_relative 'swagger_petstore_open_api30/controllers/store_controller'
require_relative 'swagger_petstore_open_api30/controllers/user_controller'
